# Generated by Django 4.2.20 on 2025-04-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_tipomedida_descripcion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="estado",
            field=models.CharField(
                choices=[
                    ("sin_iniciar", "Sin iniciar"),
                    ("en_progreso", "En progreso"),
                    ("finalizado", "Finalizado"),
                    ("atrasado", "Atrasado"),
                ],
                default="sin_iniciar",
                max_length=20,
            ),
        ),
    ]
