# Generated by Django 4.2.20 on 2025-04-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_insert_update_usuario_conaf'),
    ]

    operations = [
        migrations.AddField(
            model_name='medida',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organismosectorial',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='planorganismosectorial',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reporte',
            name='evidencia',
            field=models.CharField(default='Evidencia entregada', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporte',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tipomedida',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
