# Generated by Django 5.1.5 on 2025-01-31 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganismoSectorial',
            fields=[
                ('id_organismo_sectorial', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('responsable', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMedida',
            fields=[
                ('id_tipo_medida', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id_media', models.AutoField(primary_key=True, serialize=False)),
                ('medida', models.CharField(max_length=100, unique=True)),
                ('indicador', models.CharField(max_length=100)),
                ('forma_calculo', models.CharField(max_length=100)),
                ('medida_verificador', models.CharField(max_length=100)),
                ('id_tipo_medida', models.ForeignKey(db_column='id_tipo_medida', on_delete=django.db.models.deletion.DO_NOTHING, to='api.tipomedida')),
            ],
        ),
    ]
