# Generated by Django 4.2.18 on 2025-02-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="medida",
            old_name="medida_verificador",
            new_name="frecuencia_reporte",
        ),
        migrations.AddField(
            model_name="medida",
            name="medios_verificacion",
            field=models.CharField(default="Actualizar", max_length=200),
        ),
        migrations.AlterField(
            model_name="medida",
            name="forma_calculo",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="medida",
            name="indicador",
            field=models.CharField(max_length=200),
        ),
    ]
