# Generated by Django 4.2.20 on 2025-04-06 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_item"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanOrganismoSectorial",
            fields=[
                (
                    "id_plan_organismo_sectorial",
                    models.AutoField(primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="medida",
            name="medida",
        ),
        migrations.AddField(
            model_name="medida",
            name="nombre_corto",
            field=models.CharField(default="Actualizar", max_length=100),
        ),
        migrations.AddField(
            model_name="medida",
            name="tipo_regulatoria",
            field=models.CharField(default="Actualizar", max_length=100),
        ),
        migrations.CreateModel(
            name="Reporte",
            fields=[
                ("id_reporte", models.AutoField(primary_key=True, serialize=False)),
                (
                    "valor_reportado",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("fecha_reporte", models.DateField()),
                (
                    "id_plan_organismo_sectorial",
                    models.ForeignKey(
                        db_column="id_plan_organismo_sectorial",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.planorganismosectorial",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="planorganismosectorial",
            name="id_media",
            field=models.ForeignKey(
                db_column="id_media",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.medida",
            ),
        ),
        migrations.AddField(
            model_name="planorganismosectorial",
            name="id_organismo_sectorial",
            field=models.ForeignKey(
                db_column="id_organismo_sectorial",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.organismosectorial",
            ),
        ),
        migrations.AddField(
            model_name="planorganismosectorial",
            name="id_plan",
            field=models.ForeignKey(
                db_column="id_plan",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.plan",
            ),
        ),
    ]
