# Generated by Django 4.2.20 on 2025-04-08 02:12
from django.contrib.contenttypes.models import ContentType
from django.db import migrations

def crear_roles(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    roles = {
        "Administrador": ["add_medida", "change_medida", "delete_medida", "view_medida", "change_reporte", "delete_reporte", "view_reporte"], 
        "OrganismoSectorial": ["add_reporte", "view_reporte"], }

    for role, permisos in roles.items():
        group, _ = Group.objects.get_or_create(name=role)
        for permiso in permisos:
            model_name = permiso.split("_")[-1]
            content_type, _ = ContentType.objects.get_or_create(
                app_label="api", model=model_name
            )
            permission, _ = Permission.objects.get_or_create(
                codename=permiso, content_type_id=content_type.id
            )
            group.permissions.add(permission)


def eliminar_roles(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=["Administrador", "OrganismoSectorial"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_planorganismosectorial_remove_medida_medida_and_more"),
    ]

    operations = [
        migrations.RunPython(
            crear_roles,
            eliminar_roles
        )
    ]
