# Generated by Django 4.2.20 on 2025-04-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_item_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tipomedida",
            name="descripcion",
            field=models.TextField(),
        ),
    ]
