# Generated by Django 4.2.20 on 2025-04-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_medida_created_at_organismosectorial_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medida",
            name="forma_calculo",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="medida",
            name="frecuencia_reporte",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="medida",
            name="indicador",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="medida",
            name="medios_verificacion",
            field=models.CharField(default="Actualizar", max_length=300),
        ),
        migrations.AlterField(
            model_name="medida",
            name="nombre_corto",
            field=models.CharField(default="Actualizar", max_length=300),
        ),
        migrations.AlterField(
            model_name="medida",
            name="tipo_regulatoria",
            field=models.CharField(default="Actualizar", max_length=300),
        ),
    ]
