# Generated by Django 5.1.5 on 2025-04-09 13:48

from django.db import migrations
from django.contrib.auth.models import User

def create_or_update_superuser(apps, schema_editor):
    # Verifica si ya existe un superusuario con el nombre de usuario 'admin'
    superuser, created = User.objects.get_or_create(username='admin')
    
    # Si el superusuario ya existe, actualiza su correo y contraseña
    if not created:
        superuser.email = 'admingrupo4@backendpython.com'
        superuser.set_password('123456')
        superuser.save()
    else:
        # Si el superusuario no existía, lo crea
        superuser.set_password('123456')
        superuser.email = 'admingrupo4@backendpython.com'
        superuser.is_staff = True
        superuser.is_superuser = True
        superuser.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_medida_forma_calculo_and_more'),
    ]

    operations = [
        migrations.RunPython(create_or_update_superuser),
    ]
